wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.7
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709839665.669812
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.11.4
      5: 0.15.7
      6: 4.35.0
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: test_loss_step
      5: 1
      6:
      - 1
    - 1: conf_mat._type
      5: 1
      6:
      - 1
    - 1: conf_mat.sha256
      5: 1
      6:
      - 1
    - 1: conf_mat.size
      5: 1
      6:
      - 1
    - 1: conf_mat.path
      5: 1
      6:
      - 1
    - 1: conf_mat.format
      5: 1
      6:
      - 1
    - 1: conf_mat.width
      5: 1
      6:
      - 1
    - 1: conf_mat.height
      5: 1
      6:
      - 1
    - 1: attentions._type
      5: 1
      6:
      - 1
    - 1: attentions.sha256
      5: 1
      6:
      - 1
    - 1: attentions.size
      5: 1
      6:
      - 1
    - 1: attentions.path
      5: 1
      6:
      - 1
    - 1: attentions.format
      5: 1
      6:
      - 1
    - 1: attentions.width
      5: 1
      6:
      - 1
    - 1: attentions.height
      5: 1
      6:
      - 1
    - 1: test_BinaryAccuracy
      5: 1
      6:
      - 1
    - 1: test_BinaryPrecision
      5: 1
      6:
      - 1
    - 1: test_BinaryRecall
      5: 1
      6:
      - 1
    - 1: test_BinaryF1Score
      5: 1
      6:
      - 1
    - 1: test_loss_epoch
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
learning_rate:
  desc: null
  value: 0.0001
attn_head:
  desc: null
  value: 1
encoder_layers:
  desc: null
  value: 2
n_class:
  desc: null
  value: 3060
